### ISSUE TITLE
perl version requirement

### ISSUE THREAD

**Issue by birdhumming** [jhthorsen/net-isc-dhcpd#13]
Hello, I've been using a home-grown omap script to manage DHCP host/lease, now want to use Net-ISC-DHCPd with server upgrade. We have Redhat Linux 6.5 which comes with perl 5.10, we try not to install our own perl  instead using the one comes with Redhat linux.

So my question is, will this module works with perl 5.10, or it has to be 5.12?

**Comment by rfdrake** [comment]
About a year ago I tried to test all versions of perl I could from 5.8 -> 5.2x to make sure we were compatible.  At that point I noticed that the code didn't work on anything lower than 5.12 and that is when I set the minimum version to 5.12.5.  That was commit 9ea71554587c23dbdb2911366285ed5c49a0e4bf

I'll take a look and see if I can find a workaround when I have a chance.

**Comment by birdhumming** [comment]
Unfortunately,  RHEL 6 ships with older version perl, 5.10.
 
I believe RHEL 6  is still most popular version of RHEL currently, and it's a pain to build your version of perl just because of this package. If you can take a look and make it work with perl 5.10, will be greatly appreciated!

**Comment by jhthorsen** [comment]
@birdhumming: You should free yourself from system perl and use plenv or perlbrew instead.

* http://perlbrew.pl/
* https://github.com/tokuhirom/plenv

**Comment by birdhumming** [comment]
I've changed the requirements back to 5.8 in this file  lib/Net/ISC/DHCPd.pm, and everything seems working fine on my RHEL 6 with perl 5.10, at least for the OMAPI part, which is really the only thing I need -  I can omapi to dhcp server do things like add host/lookup lease. 

If you can let me know which part of the test with older version 5.10 of  that's broken because of getpos, I can test on my system. 

Thanks for the hint, I've already installed perl 5.12 under my homedir, but still prefer to use system perl:)

**Comment by rfdrake** [comment]
I just tested with 5.10.1 again.  At some point I removed the code that was using getpos() which means the main codebase works with 5.10.1 without issue.  I've changed it back to v5.10.1 in master.
