### ISSUE TITLE
Unable to parse config with trailing comments

### ISSUE THREAD

**Issue by b00s1** [jhthorsen/net-isc-dhcpd#16]
Writing comments in the config file is allowed almost anywhere.

From the man page:
"Comments may be placed anywhere within the file (except within quotes).   Comments begin with the # character and end at the end of the line."

Parsing test.trailing-comments.conf fails:
default-lease-time 3600;
max-lease-time 3600;
option domain-name "foobar.com";
option domain-name-servers 10.0.0.11, 10.0.0.12;
option time-servers 10.0.0.13,10.0.0.14;
option ntp-servers 10.0.0.20,10.0.0.14;

authoritative;
deny client-updates;
log-facility local6;
omapi-port 7911;

set vendorclass = option vendor-class-identifier;

ddns-update-style none; ddns-updates off;

subnet 10.1.10.0 netmask 255.255.255.0 { 
  option broadcast-address 10.1.10.255;
  option routers 10.1.10.1;
  option subnet-mask 255.255.255.0;     # parsing this comment fails blaming the next lines
  option domain-name-servers 10.1.10.11, 10.1.10.12;
  if substring (option vendor-class-identifier,0,9) = "PXEClient" {
    filename "pxelinux.0";
  }
  host testhost01 {hardware ethernet 00:01:02:03:04:01;fixed-address 10.1.10.21;}
  host testhost02 {hardware ethernet 00:01:02:03:04:02;fixed-address 10.1.10.22;}
}

subnet 10.2.10.0 netmask 255.255.255.0 {
  option broadcast-address 10.2.10.255;
  option routers 10.2.10.1;
  option subnet-mask 255.255.255.0;
  option domain-name-servers 10.1.10.11, 10.1.10.12;
  if substring (option vendor-class-identifier,0,9) = "PXEClient" {
    filename "pxelinux.0";
  }
  host testhost03 {hardware ethernet 00:01:02:03:04:03;fixed-address 10.2.10.21;}
  host testhost04 {hardware ethernet 00:01:02:03:04:04;fixed-address 10.2.10.22;}
}

**Comment by rfdrake** [comment]
merged #17
