### ISSUE TITLE
mac address regex requires leading zeros

### ISSUE THREAD

**Issue by sladiwala** [jhthorsen/net-isc-dhcpd#18]
0:0:c0:5d:bd:95 appears in one of ISC DHCPd example configuration files.
The regex in Net/ISC/DHCPd/Types.pm
```perl
subtype Mac, as Str,
    where { /^[a-f0-9:]{17}$/i };
```
doesn't match this MAC address.

**Comment by rfdrake** [comment]
well, that's what I get for cheating at validation :)
