### ISSUE TITLE
Includes in subnet block are processed as KeyValues

### ISSUE THREAD

**Issue by jesusbagpuss** [jhthorsen/net-isc-dhcpd#29]
When this module encounters an include as part of a subnet block e.g.
```
subnet 10.11.21.0 netmask 255.255.255.224 {
        option routers 10.11.21.221;
        include "/etc/local/dhcpd/current/10.11.21_24.hosts.conf";
}
```
the include is parsed as a KeyValue, not an Include.

There may be similarities with this comment: https://github.com/jhthorsen/net-isc-dhcpd/issues/26#issuecomment-221070171 - where a module wasn't expecting a specific child type to be present.

**Comment by rfdrake** [comment]
Sorry it took so long to get to this.  I just saw the email about it.
