### ISSUE TITLE
use of $config->add_host

### ISSUE THREAD

**Issue by sibelle-labs** [jhthorsen/net-isc-dhcpd#34]
Can you tell me how to use add_host ?

    $dhcpd->config->add_host({
        name => 'foo',
        hardwareethernet => "F8:75:A4:AA:7C:AA",
        fixedaddress => "172.1.2.31" ,
        filenames => [{ file => 'pxelinux.0' }],
    });

returns ...

host foo {
    filename pxelinux.0;
}

Thanks a lot

**Comment by jhthorsen** [comment]
There is an example in the unit test:

https://github.com/jhthorsen/net-isc-dhcpd/blob/97f0f4749c72642b86427af39cddf5d91acf14b6/t/10-config-generate.t#L55

Hope that works out for you.

**Comment by sibelle-labs** [comment]
Hi Jan !
Perfect ! 💯  Thanks a lot 👍 

now, the last one ...

if ( $config->find_hosts( { name             => $host } ) ); # works
if ( $config->find_hosts( { hardwareethernet => $hw } ) ); # works

but  ...

if ( $config->find_hosts( { fixedaddress     => $ip } ) );  # not working ...

I confess , all tests reviewed but nothing about this found  :-)
